workflows:
  ios_release:
    name: iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_IDENTIFIER: com.example.voicebubble
        TEAM_ID: 7T3XFY333F
    scripts:
      - name: Clean Flutter
        script: flutter clean
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build iOS (no codesign)
        script: flutter build ios --release --no-codesign
      - name: Build IPA with export options
        script: flutter build ipa --release --export-options-plist export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - you@example.com
        on_success: true
        on_failure: true
